### PR TITLE
Implementation of the translatable interface.

### PR DESCRIPTION
**Pull request by laurentmuller**
This is the PR for the feature #221.

### CODE REVIEW

**Review by ogizanagi — APPROVED** [review]
I like this. Could you please add a section describing this and the usage in the README.md file ?

**Comment by laurentmuller** [comment]
Thank You. I will update the `README.md` file.

**Review by ogizanagi — APPROVED** [review]

**Comment by ogizanagi** [comment]
Thank you @laurentmuller.

**Comment by laurentmuller** [comment]
You'r welcome.

**Comment by laurentmuller** [comment]
Any release ?

**Comment by IonBazan** [comment]
I think we should add some tests for this 🤔

**Comment by norkunas** [comment]
Since https://github.com/symfony/symfony/pull/50931 if `TranslatableInterface` would be used instead of `TranslatableEnumInterface` there would be no need to have a `Elao\Enum\Bridge\Symfony\Form\Type\EnumType` and directly use one from Symfony.

edit: missed that `TranslatableEnumInterface` extends `TranslatableInterface`. Just don't see any point from that interface

**Pull request merged**
