### PR TITLE
Fix AbstractEnumType convertToDatabase function to support string|int

### LINKED ISSUE #199: [2.X] Doctrine AbstractEnumType
Hello, 

I use your bundle in a project with symfony6.1 / doctrine 2.13.3.

Doctrine cast automatically BackEndEnum to their value : 
https://github.com/doctrine/orm/blob/06c77cebb5aa7ee3cb57f8cc0d2224538de154d7/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php#L2002

In your AbstractEnumType method convertToPhpValue check if is a BackEnum but doctrine cast before to Enum type :
https://github.com/Elao/PhpEnums/blob/a2966732d34c09093fe821ee424ac59a214bc618/src/Bridge/Doctrine/DBAL/Types/AbstractEnumType.php#L57

I have to override generated Type to avoid this method.

Step to reproduce : 
Doing a findBy with Enum criteria : 
```
       $this->eventRepository->findBy([
            'eventType' => EventType::SESSION
        ]);

```
Have you any clean solution for me ?

Thanks

### PR DESCRIPTION
**Pull request by michnovka**
Fixes https://github.com/Elao/PhpEnums/issues/199

### CODE REVIEW

**Comment by michnovka** [comment]
Lets wait before merging, I have opened a doctrine issue and I have some idea how this might be fixed on Doctrine level - https://github.com/doctrine/orm/issues/10432

But we have to see whether its decided to fix there or not.

**Comment by ogizanagi** [comment]
Thanks for opening this and the issue on the Doctrine repository 🙏🏻

**Comment by jroszkiewicz** [comment]
Hey guys, any chance for merge that? I think we can't depend on doctrine team :(

**Comment by ogizanagi** [comment]
Thanks @michnovka.

**Pull request merged**
